### ISSUE TITLE
4-4-8 and other workouts

### ISSUE THREAD

**Issue by BrandonKMLee** [thomasmarkiewicz/bodysculpting#4]
https://www.drworkout.fitness/ivysaur-4-4-8-program/

Also this application is a good template on how to copyStronglifts 5x5's UX for other workouts
https://play.google.com/store/apps/details?id=com.maxworkoutcoach.workouttrainer.workouttrainer

**Comment by thomasmarkiewicz** [comment]
I suggest we leave this issue small, specifically for adding the ivysaur-4-4-8 program. 

@BrandonKMLee , can you create separate issues for each other program you would like to see implemented?

**Comment by BrandonKMLee** [comment]
Got it.
