### ISSUE TITLE
Reference on other FOSS apps

### ISSUE THREAD

**Issue by BrandonKMLee** [thomasmarkiewicz/bodysculpting#5]
One of the other apps that are https://github.com/brodeurlv/fastnfitness

**Comment by trycatch007** [comment]
Thank you @BrandonKMLee - I'm aware of that app. I don't understand what this issue is about, can you provide more details?

**Comment by BrandonKMLee** [comment]
Reference in the documentation about the other app existing, and also comment on possible weight and body tracking

**Comment by thomasmarkiewicz** [comment]
I don't feel this app, or any other similar apps, need to be referenced in Body Sculpting app documentation.   I don't want to single out any particular projects and possibly ignore others I'm not aware of. It's not the place to create favorites here.
